# ML Zoomcamp 
## Homework #1

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import wget

print(pd.__version__)

2.0.3


Q1 What's the version of Pandas that you installed?
2.0.3


In [7]:
import urllib.request

url = 'https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv'
filename = './data/housing.csv'

urllib.request.urlretrieve(url, filename)

('./data/housing.csv', <http.client.HTTPMessage at 0x27a87138f40>)

In [8]:
df = pd.read_csv(filename, header=0)
df.shape

(20640, 10)

Q2 - How many columns are in the dataset?

In [9]:

df.shape[1]

# 10

10

Q3 - Which columns in the dataset have missing values?

In [10]:

df.isnull().any()

# total_bedrooms has missing values

longitude             False
latitude              False
housing_median_age    False
total_rooms           False
total_bedrooms         True
population            False
households            False
median_income         False
median_house_value    False
ocean_proximity       False
dtype: bool

Q4 - How many unique values does the ocean_proximity column have?

In [12]:
df.ocean_proximity.nunique()

#5

5

 Q5 - What's the average value of the median_house_value for the houses located near the bay?

In [16]:

df[df.ocean_proximity == 'NEAR BAY']['median_house_value'].mean()

# 259212


Object `bay` not found.


259212.31179039303

Q6 
Calculate the average of total_bedrooms column in the dataset.
Use the fillna method to fill the missing values in total_bedrooms with the mean value from the previous step.
Now, calculate the average of total_bedrooms again.
Has it changed?

No

In [17]:
df.total_bedrooms.mean()

537.8705525375618

In [20]:
df['total_bedrooms'] = df['total_bedrooms'].fillna(df.total_bedrooms.mean())


In [21]:
df.total_bedrooms.mean()

537.8705525375617

Q7
Select all the options located on islands.
Select only columns housing_median_age, total_rooms, total_bedrooms.
Get the underlying NumPy array. Let's call it X.
Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
Compute the inverse of XTX.
Create an array y with values [950, 1300, 800, 1000, 1300].
Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
What's the value of the last element of w?



#5.6992

In [24]:
df.ocean_proximity.value_counts()

ocean_proximity
<1H OCEAN     9136
INLAND        6551
NEAR OCEAN    2658
NEAR BAY      2290
ISLAND           5
Name: count, dtype: int64

In [42]:
X = df[df['ocean_proximity']=='ISLAND'][['housing_median_age','total_rooms','total_bedrooms']].to_numpy()
XTX = X.T.dot(X)
XTX = np.linalg.inv(XTX)
XTX

array([[ 9.19403586e-04, -3.66412216e-05,  5.43072261e-05],
       [-3.66412216e-05,  8.23303633e-06, -2.77534485e-05],
       [ 5.43072261e-05, -2.77534485e-05,  1.00891325e-04]])

In [46]:
X

array([[  27., 1675.,  521.],
       [  52., 2359.,  591.],
       [  52., 2127.,  512.],
       [  52.,  996.,  264.],
       [  29.,  716.,  214.]])

In [43]:
y = np.array([950, 1300, 800, 1000, 1300])
y

array([ 950, 1300,  800, 1000, 1300])

In [44]:
w = XTX.dot(X.T).dot(y)
w

array([23.12330961, -1.48124183,  5.69922946])

In [47]:
w[-1]

5.6992294550655656